service: DynamoTest
plugins:
  - serverless-prune-plugin
custom:
  prune:
    automatic: true
    number: 5

provider:
  name: aws 
  runtime: nodejs18.x
  region: us-east-1
  role: arn:aws:iam::905418069528:role/LabRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sts:AssumeRole
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:us-east-1:*:table/Agendamiento
        - arn:aws:dynamodb:us-east-1:*:table/Agendamiento/index/*

functions:
  poblarDynamo:
    handler: src/simulador.poblarDynamo
    timeout: 60      
    memorySize: 1024  
    environment:
      TABLE: Agendamiento
    events:
      - httpApi:
          path: /agendamiento
          method: post

  
  getAgendamientos:
    handler: src/consulta.getConsultas
    environment:
      TABLE: Agendamiento
    events:
      - httpApi:
          path: /agendamiento
          method: get

  obtenerAgendamientosPorPaciente:
    handler: src/agendamientoPorPaciente.obtenerAgendamientosPorPaciente
    events:
      - http:
          path: agendamientos/paciente/{pacienteId}
          method: get
          cors: true

  agendamientoPorBox:
    handler: src/agendamientoPorBox.obtenerAgendamientosPorBox
    events:
      - http:
          path: agendamientos/box/{boxId}
          method: get
          cors: true        
  
  obtenerBox:
    handler: src/obtenerBoxPorId.obtenerBoxPorId
    events:
      - http:
          path: box/{boxId}
          method: get
          cors: true



resources:
  Resources:
    AgendamientoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Agendamiento
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: PacienteId
            AttributeType: S
          - AttributeName: FechaPaciente
            AttributeType: S
          - AttributeName: FuncionarioId
            AttributeType: S
          - AttributeName: FechaFuncionario
            AttributeType: S
          - AttributeName: BoxId
            AttributeType: S
          - AttributeName: FechaBox
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: AgendamientosPorPaciente
            KeySchema:
              - AttributeName: PacienteId
                KeyType: HASH
              - AttributeName: FechaPaciente
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: AgendamientosPorFuncionario
            KeySchema:
              - AttributeName: FuncionarioId
                KeyType: HASH
              - AttributeName: FechaFuncionario
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: AgendamientosPorBox
            KeySchema:
              - AttributeName: BoxId
                KeyType: HASH
              - AttributeName: FechaBox
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
